### ISSUE TITLE
How does Rails handle production worth error pages? 500, 404 ...

### ISSUE THREAD

**Issue by EdenVicary** [EdenVicary/ruby-training#5]

**Comment by felixclack** [comment]
Static pages.

`public/404.html`
`public/500.html`

**Comment by EdenVicary** [comment]
So what about for those errors you get when you're missing a class or something?

**Comment by felixclack** [comment]
Production doesn't show those errors to your user. They get a 500.

You need to setup some kind of exception notification system to notify you of the specific error.

eg. https://github.com/smartinez87/exception_notification

Or use an addon https://addons.heroku.com/#errors-exceptions

**Comment by EdenVicary** [comment]
Ok cool
