### ISSUE TITLE
Clean branching

### ISSUE THREAD

**Issue by EdenVicary** [EdenVicary/ruby-training#6]
How would you manage branching? Like cleaning up all the old branches from pull requests and the various branches you don't use. Is that something we care about?

**Comment by felixclack** [comment]
I usually click the delete button on GitHub after merging.

Then locally I will delete the branch after I have pulled from master.

**Comment by EdenVicary** [comment]
Ok cool, so every branch should have a reason? If say I had a branch in there that existed from before the pull requests that I am not using anymore I should just delete it?

**Comment by felixclack** [comment]
Yeah, unless you’re using it still.


—
Thanks,
Felix

**Comment by EdenVicary** [comment]
I went through and cleaned up all my  old branches!! looks good now
