### ISSUE TITLE
What do you think about https://hakiri.io/ ?

### ISSUE THREAD

**Issue by EdenVicary** [EdenVicary/ruby-training#9]

**Comment by felixclack** [comment]
Looks good.

Anything that can help alert you about common (sometimes stupid) mistakes is a good thing.

**Comment by felixclack** [comment]
There are a couple of gems that do similar things, https://github.com/presidentbeef/brakeman and https://github.com/rubysec/bundler-audit

**Comment by EdenVicary** [comment]
Cool
